### ISSUE TITLE
Add RegEx as a SortingMethod

### ISSUE THREAD

**Issue by charlie-daniels** [charlie-daniels/ren#2]
## Description
Implement a search function so the user can select certain files from a directory using more specific options.

## TODO
- [ ] Add REGEX to the SortingMethod enum
- [ ] Query user and parse the RegEx used
- [ ] Apply logic to handle_sort function
- [ ] Include regex for file extensions
